### ISSUE TITLE
Double draw of ants

### ISSUE THREAD

**Issue by KorraOne** [CodeCr4fter/ant_simulation#1]
https://github.com/CodeCr4fter/ant_simulation/blob/b270d78d935857eaa42a59d5ff6a8964d9c3acf4/main.py#L282 Is there a reason for the drawing of the ants twice or just an oversight? 
I imagine looping over all the ant objects and rendering them would hurt performance of the simulation. So if it isn't needed that will help.

**Comment by CodeCr4fter** [comment]
Just an oversight. Thanks for noticing.
